apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: codingground-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: codingground-backend
        image: 503237308475.dkr.ecr.ca-central-1.amazonaws.com/codingground-backend:v0.1.0
        ports:
        - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: codingground-backend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: backend
