apiVersion: apps/v1
kind: Deployment
metadata:
  name: codingground-backend
  namespace: codingground-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: codingground-backend
        image: 503237308475.dkr.ecr.ca-central-1.amazonaws.com/codingground-backend:v0.2.2
        ports:
        - containerPort: 8090