#apiVersion: v1
#kind: Service
#metadata:
#  name: backend-rule
#  annotations:
#    alb.ingress.kubernetes.io/healthcheck-path: "/"
#spec:
#  selector:
#    app: backend
#  type: NodePort
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80